# Generated by Django 5.1.3 on 2024-11-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_registrocomunion_persona_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bautizo',
            old_name='fecha',
            new_name='fecha_bautizo',
        ),
        migrations.RenameField(
            model_name='comunion',
            old_name='fecha',
            new_name='fecha_comunion',
        ),
        migrations.RenameField(
            model_name='confirmacion',
            old_name='fecha',
            new_name='fecha_confirmacion',
        ),
        migrations.RenameField(
            model_name='matrimonio',
            old_name='fecha',
            new_name='fecha_matrimonio',
        ),
        migrations.RemoveField(
            model_name='bautizo',
            name='iglesia',
        ),
        migrations.RemoveField(
            model_name='bautizo',
            name='padrinos',
        ),
        migrations.RemoveField(
            model_name='comunion',
            name='iglesia',
        ),
        migrations.RemoveField(
            model_name='confirmacion',
            name='iglesia',
        ),
        migrations.RemoveField(
            model_name='confirmacion',
            name='padrinos',
        ),
        migrations.RemoveField(
            model_name='matrimonio',
            name='iglesia',
        ),
        migrations.RemoveField(
            model_name='matrimonio',
            name='testigos',
        ),
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
    ]
