# Generated by Django 5.1.3 on 2024-11-12 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_fecha_bautizo_fecha_bautizo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bautizo',
            name='fecha_bautizo',
        ),
        migrations.RemoveField(
            model_name='comunion',
            name='fecha_comunion',
        ),
        migrations.RemoveField(
            model_name='matrimonio',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='bautizo',
            name='acta',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='bautizo',
            name='ano_registro_eclesiastico',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='bautizo',
            name='datos_registro_civil_acta',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='bautizo',
            name='datos_registro_civil_pagina',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='bautizo',
            name='datos_registro_civil_tomo',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='bautizo',
            name='fecha_emision_certificado_bautizo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bautizo',
            name='fecha_registro',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bautizo',
            name='madre',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='bautizo',
            name='ministro',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bautizo',
            name='nombre',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='bautizo',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bautizo',
            name='padre',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='bautizo',
            name='padrinos',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='bautizo',
            name='pagina',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='bautizo',
            name='parroco',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='bautizo',
            name='tomo',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='comunion',
            name='acta',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='comunion',
            name='ano_registro_eclesiastico',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='comunion',
            name='celebrante',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='comunion',
            name='datos_registro_civil_acta',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='comunion',
            name='datos_registro_civil_ano',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='comunion',
            name='datos_registro_civil_pagina',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='comunion',
            name='datos_registro_civil_tomo',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='comunion',
            name='fecha_emision_certificado_comunion',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='comunion',
            name='fecha_sacramento',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='comunion',
            name='madre',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='comunion',
            name='nombre',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='comunion',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comunion',
            name='padre',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='comunion',
            name='padrinos',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='comunion',
            name='pagina',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='comunion',
            name='parroco',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='comunion',
            name='tomo',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='acta',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='ano_registro_eclesiastico',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='celebrante',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='datos_registro_civil_acta',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='datos_registro_civil_ano',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='datos_registro_civil_pagina',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='datos_registro_civil_tomo',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='fecha_emision_certificado_confirmacion',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='madre',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='nombre',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='padre',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='pagina',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='parroco',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='tomo',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='matrimonio',
            name='acta',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='matrimonio',
            name='ano_registro_eclesiastico',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='matrimonio',
            name='celebrante',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='matrimonio',
            name='conyuges',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AddField(
            model_name='matrimonio',
            name='datos_registro_civil_acta',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='matrimonio',
            name='datos_registro_civil_ano',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='matrimonio',
            name='datos_registro_civil_pagina',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='matrimonio',
            name='datos_registro_civil_tomo',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='matrimonio',
            name='fecha_emision_certificado_matrimonio',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='matrimonio',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matrimonio',
            name='padrinos',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='matrimonio',
            name='pagina',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='matrimonio',
            name='parroco',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='matrimonio',
            name='testigos',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='matrimonio',
            name='tomo',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='persona',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='confirmacion',
            name='fecha_confirmacion',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AlterField(
            model_name='matrimonio',
            name='fecha_matrimonio',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Defuncion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_civil', models.CharField(default='Unknown', max_length=20)),
                ('edad', models.IntegerField(default=0)),
                ('lugar_fallecimiento', models.CharField(default='Unknown', max_length=255)),
                ('causa_fallecimiento', models.CharField(default='Unknown', max_length=255)),
                ('parroco', models.CharField(default='Unknown', max_length=255)),
                ('ano_registro_eclesiastico', models.CharField(default='Unknown', max_length=100)),
                ('tomo', models.CharField(default='Unknown', max_length=255)),
                ('pagina', models.CharField(default='Unknown', max_length=255)),
                ('acta', models.CharField(default='Unknown', max_length=100)),
                ('datos_registro_civil_ano', models.IntegerField(default=2024)),
                ('datos_registro_civil_tomo', models.CharField(default='Unknown', max_length=255)),
                ('datos_registro_civil_pagina', models.CharField(default='Unknown', max_length=255)),
                ('datos_registro_civil_acta', models.CharField(default='Unknown', max_length=255)),
                ('fecha_emision_certificado_defuncion', models.DateField(default='2024-01-01')),
                ('nota', models.TextField(blank=True, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Sepultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_civil', models.CharField(default='Unknown', max_length=20)),
                ('edad', models.IntegerField(default=0)),
                ('fecha_fallecimiento', models.DateField()),
                ('motivo_fallecimiento', models.CharField(default='Unknown', max_length=255)),
                ('parroco', models.CharField(default='Unknown', max_length=255)),
                ('fecha_sepultura', models.DateField()),
                ('ano_registro_eclesiastico', models.CharField(default='Unknown', max_length=100)),
                ('tomo', models.CharField(default='Unknown', max_length=255)),
                ('pagina', models.CharField(default='Unknown', max_length=255)),
                ('acta', models.CharField(default='Unknown', max_length=100)),
                ('datos_registro_civil_ano', models.IntegerField(default=2024)),
                ('datos_registro_civil_tomo', models.CharField(default='Unknown', max_length=255)),
                ('datos_registro_civil_pagina', models.CharField(default='Unknown', max_length=255)),
                ('datos_registro_civil_acta', models.CharField(default='Unknown', max_length=255)),
                ('fecha_emision_certificado_sepultura', models.DateField(default='2024-01-01')),
                ('parroco_certificado', models.CharField(default='Unknown', max_length=255)),
                ('nota', models.TextField(blank=True, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.persona')),
            ],
        ),
    ]
