# Generated by Django 5.1.3 on 2024-11-12 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_bautizo_fecha_bautizo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmacion',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='comunion',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='defuncion',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='sepultura',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='bautizo',
            name='persona',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
