# Generated by Django 5.1.3 on 2024-11-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_confirmacion_persona_remove_comunion_persona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunion',
            name='acta',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comunion',
            name='ano_registro_eclesiastico',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comunion',
            name='celebrante',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comunion',
            name='datos_registro_civil_acta',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comunion',
            name='datos_registro_civil_ano',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comunion',
            name='datos_registro_civil_pagina',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comunion',
            name='datos_registro_civil_tomo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comunion',
            name='fecha_emision_certificado_comunion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='comunion',
            name='fecha_sacramento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='comunion',
            name='madre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comunion',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comunion',
            name='padre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comunion',
            name='padrinos',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comunion',
            name='pagina',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comunion',
            name='parroco',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comunion',
            name='tomo',
            field=models.CharField(max_length=255),
        ),
    ]
