# Generated by Django 5.1.3 on 2024-11-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_comunion_acta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bautizo',
            name='acta',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='bautizo',
            name='ano_registro_eclesiastico',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='bautizo',
            name='datos_registro_civil_acta',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='bautizo',
            name='datos_registro_civil_pagina',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='bautizo',
            name='datos_registro_civil_tomo',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='bautizo',
            name='fecha_emision_certificado_bautizo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bautizo',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bautizo',
            name='madre',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='bautizo',
            name='ministro',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='bautizo',
            name='nombre',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='bautizo',
            name='padre',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='bautizo',
            name='padrinos',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='bautizo',
            name='pagina',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='bautizo',
            name='parroco',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='bautizo',
            name='tomo',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='confirmacion',
            name='acta',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='confirmacion',
            name='ano_registro_eclesiastico',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='confirmacion',
            name='celebrante',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='confirmacion',
            name='datos_registro_civil_acta',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='confirmacion',
            name='datos_registro_civil_pagina',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='confirmacion',
            name='datos_registro_civil_tomo',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='confirmacion',
            name='fecha_confirmacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='confirmacion',
            name='fecha_emision_certificado_confirmacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='confirmacion',
            name='madre',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='confirmacion',
            name='nombre',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='confirmacion',
            name='padre',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='confirmacion',
            name='pagina',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='confirmacion',
            name='parroco',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='confirmacion',
            name='tomo',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='defuncion',
            name='acta',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='defuncion',
            name='ano_registro_eclesiastico',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='defuncion',
            name='causa_fallecimiento',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='defuncion',
            name='datos_registro_civil_acta',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='defuncion',
            name='datos_registro_civil_pagina',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='defuncion',
            name='datos_registro_civil_tomo',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='defuncion',
            name='estado_civil',
            field=models.CharField(default='Desconocido', max_length=20),
        ),
        migrations.AlterField(
            model_name='defuncion',
            name='fecha_emision_certificado_defuncion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='defuncion',
            name='lugar_fallecimiento',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='defuncion',
            name='pagina',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='defuncion',
            name='parroco',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='defuncion',
            name='tomo',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='matrimonio',
            name='acta',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='matrimonio',
            name='ano_registro_eclesiastico',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='matrimonio',
            name='celebrante',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='matrimonio',
            name='conyuges',
            field=models.CharField(max_length=511),
        ),
        migrations.AlterField(
            model_name='matrimonio',
            name='datos_registro_civil_acta',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='matrimonio',
            name='datos_registro_civil_pagina',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='matrimonio',
            name='datos_registro_civil_tomo',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='matrimonio',
            name='fecha_emision_certificado_matrimonio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='matrimonio',
            name='fecha_matrimonio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='matrimonio',
            name='padrinos',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='matrimonio',
            name='pagina',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='matrimonio',
            name='parroco',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='matrimonio',
            name='testigos',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='matrimonio',
            name='tomo',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='sepultura',
            name='acta',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='sepultura',
            name='ano_registro_eclesiastico',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='sepultura',
            name='datos_registro_civil_acta',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='sepultura',
            name='datos_registro_civil_pagina',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='sepultura',
            name='datos_registro_civil_tomo',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='sepultura',
            name='estado_civil',
            field=models.CharField(default='Desconocido', max_length=20),
        ),
        migrations.AlterField(
            model_name='sepultura',
            name='fecha_emision_certificado_sepultura',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sepultura',
            name='motivo_fallecimiento',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='sepultura',
            name='pagina',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='sepultura',
            name='parroco',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='sepultura',
            name='parroco_certificado',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='sepultura',
            name='tomo',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
    ]
