# Generated by Django 5.1.3 on 2024-11-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_bautizo_acta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunion',
            name='datos_registro_civil_ano',
        ),
        migrations.RemoveField(
            model_name='comunion',
            name='fecha_emision_certificado_comunion',
        ),
        migrations.RemoveField(
            model_name='comunion',
            name='fecha_sacramento',
        ),
        migrations.AddField(
            model_name='comunion',
            name='fecha_emision_certificado_bautizo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comunion',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comunion',
            name='ministro',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='comunion',
            name='acta',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='comunion',
            name='ano_registro_eclesiastico',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='comunion',
            name='celebrante',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='comunion',
            name='datos_registro_civil_acta',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='comunion',
            name='datos_registro_civil_pagina',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='comunion',
            name='datos_registro_civil_tomo',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='comunion',
            name='madre',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='comunion',
            name='nombre',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='comunion',
            name='padre',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='comunion',
            name='padrinos',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='comunion',
            name='pagina',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='comunion',
            name='parroco',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='comunion',
            name='tomo',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
    ]
