# Generated by Django 5.1.3 on 2024-11-26 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_defuncion_nombre_sepultura_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comunion',
            old_name='fecha_emision_certificado_bautizo',
            new_name='fecha_emision_certificado',
        ),
        migrations.RemoveField(
            model_name='comunion',
            name='ministro',
        ),
        migrations.RemoveField(
            model_name='comunion',
            name='padrinos',
        ),
    ]
