# Generated by Django 5.1.3 on 2024-11-26 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_rename_fecha_emision_certificado_bautizo_comunion_fecha_emision_certificado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comunion',
            old_name='fecha_emision_certificado',
            new_name='fecha_emision_certificado_bautizo',
        ),
    ]
