# Generated by Django 5.1.3 on 2024-11-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_bautizo_ano_registro_civil_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bautizo',
            old_name='acta',
            new_name='acta_registro_civil',
        ),
        migrations.RenameField(
            model_name='bautizo',
            old_name='datos_registro_civil_acta',
            new_name='acta_registro_eclesiastico',
        ),
        migrations.RenameField(
            model_name='bautizo',
            old_name='datos_registro_civil_pagina',
            new_name='cedula_registro_civil',
        ),
        migrations.RenameField(
            model_name='bautizo',
            old_name='datos_registro_civil_tomo',
            new_name='celebrante',
        ),
        migrations.RenameField(
            model_name='bautizo',
            old_name='fecha_emision_certificado_bautizo',
            new_name='fecha_bautizo',
        ),
        migrations.RenameField(
            model_name='bautizo',
            old_name='fecha_registro',
            new_name='fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='bautizo',
            old_name='ministro',
            new_name='lugar_nacimiento',
        ),
        migrations.RenameField(
            model_name='bautizo',
            old_name='pagina',
            new_name='pagina_registro_civil',
        ),
        migrations.RenameField(
            model_name='bautizo',
            old_name='parroco',
            new_name='pagina_registro_eclesiastico',
        ),
        migrations.RenameField(
            model_name='bautizo',
            old_name='tomo',
            new_name='tomo_registro_civil',
        ),
        migrations.AddField(
            model_name='bautizo',
            name='tomo_registro_eclesiastico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
