# Generated by Django 5.1.3 on 2024-11-26 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_rename_acta_confirmacion_acta_registro_civil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmacion',
            name='cedula_registro_civil',
        ),
    ]
