# Generated by Django 5.1.3 on 2024-12-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_remove_matrimonio_cedula_registro_civil'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacion',
            name='padrinos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
